image: "internal/mamido/ci-runner-base:buster"

stages: [build]

variables:
  PLUGIN_VERSION: "0.1.2"
  PACKAGE_GLOB: "build/libs/*.jar"

build_jar:
  stage: build
  script:
    - DEFAULT_JVM_OPTS="-Dhttp.proxyHost=itproxy.1and1.org -Dhttp.proxyPort=3128 -Dhttps.proxyHost=itproxy.1and1.org -Dhttps.proxyPort=3128"
    - ./gradlew clean test jar
  artifacts:
    expire_in: 2 weeks
    paths:
      - $PACKAGE_GLOB
