image: "internal/mamido/ci-runner-base:buster"

stages: [build]

variables:
  PLUGIN_VERSION: "0.1.2"
  PACKAGE_GLOB: "build/libs/*.jar"

build_jar:
  stage: build
  script:
    - ui_proxy_on
    - https_proxy='http://itproxy.1and1.org:3128' http_proxy='http://itproxy.1and1.org:3128' ./gradlew clean test jar
  artifacts:
    expire_in: 2 weeks
    paths:
      - $PACKAGE_GLOB
